### ISSUE TITLE
Provide a workflow command to upload an artifact so we can upload artifacts inside other actions

### ISSUE THREAD

**Issue by TravisEz13** [actions/upload-artifact#105]
I don't see one in the list here:
https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions

**Comment by konradpabjan** [comment]
If you want to upload artifacts in other actions, you can use the `@actions/artifact` NPM package 😃 https://github.com/actions/toolkit/tree/main/packages/artifact

This action is effectively just a wrapper for the package. The core upload logic alongside all the necessary API calls are all taken care of inside there.

**Comment by TravisEz13** [comment]
We are trying to write actions in PowerShell.  Calling back into node is painful.

**Comment by konradpabjan** [comment]
You can call the node package in a shell script using something like [this](https://github.com/actions/toolkit/blob/ccad19055eadcd85dd8bf73a487385c9c7233b4e/.github/workflows/artifact-tests.yml#L62) (I do not recommend this hack in any way 😄). There is however a problem though because certain env variables are only available in the node context (the context is [this](https://github.com/actions/upload-artifact/blob/5f948bc1f0a251f88bb4c9b1c3dfa6cbd1327dc5/action.yml#L12) thing when you author actions). We get around this by running a local action [here](https://github.com/actions/toolkit/blob/ccad19055eadcd85dd8bf73a487385c9c7233b4e/.github/workflows/artifact-tests.yml#L32) (another hack just so we could get some CI working). So if you're dealing with pure powershell, it most likely will not work. Some more info [here](https://github.com/actions/toolkit/blob/ccad19055eadcd85dd8bf73a487385c9c7233b4e/packages/artifact/__tests__/ci-test-action/index.js#L1).

We have a feature on the horizon though might be able to help you out: https://github.com/actions/runner/issues/438

**Comment by TravisEz13** [comment]
The composable actions seems like a better option

**Comment by konradpabjan** [comment]
Composite actions have shipped! https://github.blog/changelog/2020-08-07-github-actions-composite-run-steps/

Going to close out this issue now
