### ISSUE TITLE
Rename v2 release to v2.0.0

### ISSUE THREAD

**Issue by EwoutH** [actions/upload-artifact#184]
**Describe the bug**
Currently GitHub thinks the `v2` release is the latest release. This causes some unexpected behaviour if you use `actions/upload-artifact@v2`, thinking you get the actual latest release (which is `v2.2.2`). Therefore I would propose to rename the `v2` release to `v2.0.0`, so that a plain `@v2` references the latest stable v2.x.x release again.

**Version**
- V2

**Environment**
- all

**Run/Repo Url**
https://github.com/actions/upload-artifact/releases

**Screenshots**
<img width="797" alt="Screenshot_419" src="https://user-images.githubusercontent.com/15776622/112829144-faa8f800-9090-11eb-8fcc-b80ab4f89ee1.png">

**Comment by The-Compiler** [comment]
As seen on your screenshot, v2 and v2.2.2 seem to point to the same commit, though?

**Comment by EwoutH** [comment]
It looks like it has been modified afterwards, maybe even on each release. Renaming it to v2.0.0 would let GitHub Actions recognize v2.2.2 (currently) as the latest release.

**Comment by The-Compiler** [comment]
But that's how [tagging with GitHub Actions](https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management) usually works, no?

> - Create a release using semantic versioning.
> - Move the major version tag (such as `v1`, `v2`) to point to the Git ref of the current release.

**Comment by EwoutH** [comment]
Apparently, but I haven't seen any major actions do it this way. Almost all follow just semantic versioning and never tag (or re-tag) a plain `v2` tag without specifying its minor and patch version.

**Comment by konradpabjan** [comment]
I've gone ahead and deleted the release for the `v2` tag (I should not have created a release for that in the first place, should have been just a tag). Thanks for reporting this. Fixed this in a few other first party actions as well.

The repo overview now correctly shows the most recent release. Previously `v2` with a much older release date would show up here.

![image](https://user-images.githubusercontent.com/16109154/114453647-b85edb00-9ba7-11eb-8e36-7e74a300fa66.png)

Whenever there is a new release, the major tag `v2` or `v1` get updated to point to the same SHA as the latest release. Most users just pin to `@v2` instead of a specific version like `@v2.2.1` so we follow this process so no one has to update their YAML file.

![image](https://user-images.githubusercontent.com/16109154/114453551-a3824780-9ba7-11eb-92dd-b035ad7f3ef1.png)

**Comment by EwoutH** [comment]
@konradpabjan Do you think the [action-versioning.md](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md) document over at [actions/toolkit](https://github.com/actions/toolkit) should also be updated?
