### ISSUE TITLE
Name Restrictions

### ISSUE THREAD

**Issue by Stanzilla** [actions/upload-artifact#22]
Currently facing this issue where I want the name of the PR in the name of the artifact, but 

`##[error]Artifact name is not valid: WeakAuras-Companion-PR-fix/discord-channel-Node10. It cannot contain '\', '/', "', ':', '<', '>', '|', '*', and '?'`

any chance you guys can escape this?

**Comment by konradpabjan** [comment]
This restriction on artifact names is by design and we don't plan on adding support for anything like escaping.

The reason for this restriction is because we have to be file-system agnostic. Ideally the same behavior between all OSs. Most of the characters that are not allowed are restrictions with NTFS. The `:` character also has some restrictions with macOS.

When an artifact is uploaded with `ubuntu-latest` for example. We want to ensure that it can then be downloaded properly on Windows or Mac. We don't want to introduce anything that requires someone who is downloading the artifact to have the know the file system type or OS. We also don't want to introduce escaping or any sort of file path manipulations

**Comment by findepi** [comment]
I currently use `actions/upload-artifact@v2` and the artifact name includes matrix's option so that i distinguish between artifacts
```
name: results for ${{ matrix.config }}
```

obviously this fails when `config` contains things like a slash.
(The `config` variable contains a path, so it cannot just remove slash from that.)

Provided that it's not a wrong usage of the action, what would be the recommended way to handle that?

**Comment by gnb** [comment]
Hey @findepi I hit the same issue and found a workaround.

Is it the best or recommended way? I dunno, but it works for me.

I added a new step earlier in the job, which calculates a valid artifact name from matrix properties (in my case `matrix.container` and `matrix.os`, in your case `matrix.config`).  It then stashes that in an environment variable for subsequent actions to use.

```
            - name: Prepare a unique name for Artifacts
              id: prep_artifact_name
              run: |
                # Calculate a unique string which applies to the matrix entry
                # that we can use to construct unique and valid artifact names.
                # We achieve that by squashing runs of characters are invalid
                # in artifact names, and also whitespace and dashes, into a
                # single dash character.  The unique string will appear as
                # the environment variable ARTIFACT_NAME in subsequent actions.
                if [ "${{ matrix.container }}" != "" ] ; then
                    name="${{ matrix.container }}"
                else
                    name="${{ matrix.os }}"
                fi
                # The option to enable + in sed regexps differs by OS so we avoid it
                name=$(echo -n "$name" | sed -e 's/[ \t:\/\\"<>|*?]/-/g' -e 's/--*/-/g')
                echo "ARTIFACT_NAME=$name" >> $GITHUB_ENV
```

Then the action that uploads artifacts uses the env var to build the artifact name.

```
            - name: Upload test logs if failed
              uses: actions/upload-artifact@v2
              if: failure()
              with:
                name: "${{ env.ARTIFACT_NAME }}-test-logs"
                path: |
                    tests/t*.log
                    tests/t*.ee
```
