### ISSUE TITLE
Files with colons in the name are missing in the artifact.

### ISSUE THREAD

**Issue by nickelc** [actions/upload-artifact#35]
The upload is successful but files with colons in the name are missing in the artifact.

https://github.com/nickelc/azure-test/runs/311758340#step:5:8
```
Run actions/upload-artifact@v1
  with:
    name: docs
    path: docs
Uploading artifact 'docs' from '/home/runner/work/azure-test/azure-test/docs' for run #80
Uploading 125 files
Total file: 125 ---- Processed file: 2 (1%)
Fail to upload '/home/runner/work/azure-test/azure-test/docs/modio::Filehash.md' due to 'TF10123: The path 'docs/modio::Filehash.md' contains the character ':'. Remove the ':' and try again.'.
GitHub.Services.Common.VssServiceException: TF10123: The path 'docs/modio::Filehash.md' contains the character ':'. Remove the ':' and try again.
```

The files are coming from a cloned [wiki repository](https://github.com/modio/SDK/wiki/modio%3A%3AFilehash) of a GitHub repository.
OG GitHub is not compatible with MS GitHub :grin:

**Comment by stefanhoelzl** [comment]
same here issue here
https://github.com/stefanhoelzl/bundestag_mining/commit/596937b846cfe558fc536619c3f3b2eadf349e97/checks?check_suite_id=395633375#step:6:11

any workaround to get this files in the archive?
Renaming is not possible!

It would also be good if the step fails, otherwise it is not clear that files are missing

**Comment by konradpabjan** [comment]
This has been fixed and should be deployed to everyone now. If there now is a file that cannot be uploaded, the action will fail. Here is an example run that shows the upload failing: https://github.com/konradpabjan/artifact-test/commit/9cc65436ba0f23d23226775682a6d5881d1bc398/checks?check_suite_id=400346755

We implemented a change on the backend that returns a different response code that causes the action to fail. The reason why we have this restriction to begin with is because we have to maintain platform agnostic behavior. Certain characters like `:` are not allowed in NTFS and other file systems. When you upload a file with the `:` character on Linux for example, someone may later choose to download that artifact on Windows and that would cause a lot of problems. Best solution is to just restrict certain characters from being uploaded at all which is what we have done.
