### ISSUE TITLE
Uploaded Artifacts are corrupted when downloaded

### ISSUE THREAD

**Issue by MadaraUchiha** [actions/upload-artifact#74]
## Background

[This build](https://github.com/MadaraUchiha/CombatExtended/runs/634125200) reported success in uploading approx 3000 files as artifacts, the artifact .zip file reports it is ~15MB as expected.

## Expected

When pressing the download button for the artifact it should

- Start downloading immediately
- Download a zip file of approx 15MB
- zip file to contain correct directory structure of the uploaded artifacts from the job

## Actual

- Download waits for about 30 seconds at 0 bytes/sec
- Download finishes after 64kB of data
- Resulting zip is corrupted, containing a handful of the smaller files and a bunch of empty directories.

### Note:
Workarounds welcome. At the end of the day, I want the artifact to contains all those files and in that directory structure. If giving it a zip file to upload directly would be easier than 3k individual files, or some other such workaround, I'll be happy to hear about it :)

**Comment by konradpabjan** [comment]
So it appears you're using the `v1` version of `upload-artifact`. Pointing that out since `v2` was just released and it's nearly identical.

A few things going on behind the scenes:  
- When `upload-artifact` is called, there is no zip file created. If you turn on step debugging (add a secret called `ACTIONS_STEP_DEBUG` and set the value to `true`), and run `upload-artifact`, you will see individual files being uploaded and the total time that it takes to upload each file.
- Individual files do get uploaded and later saved in our blob storage with gzip (implementation detail behind the scenes, this helps significantly speed up uploads and downloads, reduce storage that is used and this has huge perf implications especially on self-hosted runners).
- When you click to download an artifact from the UI, what is happening is that individual files first get ungzipped, and then they all get thrown together into a single folder that gets zipped and ultimately that is what gets downloaded
- When you're waiting for the download to start, this ungzipping and later zipping is happening behind the scenes as the download is preparing, so this is why there is the delay
- Why do we zip in the first place? UI limitations. We don't yet have the UI ready to browse and download files individually, so we zip everything into a single file so that everything can be downloaded at once. We have plans to enhance the UI in the future though, and once that is in place, you'll be able to download individual files with no zipping nearly immediately 

To the problem you encountered... could you retry the download 😀 It worked for me, I ended up getting about a 15MB artifact after unzipping and there doesn't appear to be any corruption. 

My guess is that when the artifact was being prepared for download, there must have been a server error or some small outage that happened.

**Comment by MadaraUchiha** [comment]
@konradpabjan Thanks for your answer!

Indeed, after about an hour, it just started to work as expected. I have also tried to add zip steps using powershell's `Compress-Archive` command, this makes the artifact work perfectly (presumably because there's only the one file) but it a. creates a zip within a zip, as the zip I upload gets zipped again, b. extends the build time very significantly.

Would upgrading to v2 work better for me? I don't expect the number of files needed as artifacts to lessen as the project evolves.

**Comment by konradpabjan** [comment]
Glad it worked! Must have been a 500 or some temporary issue that you unexpectedly hit.

`v2` has the same behavior as `v1` but it has some new features such as wildcard support. We're also planning some new things like multi-path input and only v2 will be getting the new features. 

The double-zip issue will unfortunately still happen even if you're using `v2`, there is nothing we can do on the `upload-artifact` side except to wait for UI changes that will allow you to download artifact contents individually.

`v2` is still very very new and there are a few new bugs (highly unlikely to be hit though) that recently came up that we need to address. Unless you really need wildcard support I would recommend to stay on `v1` at least for a little bit longer.

**Comment by moonburnt** [comment]
Similar problem just happened to me, except I'm using v3 - first artifact gets uploaded correctly, everything else return unreadable archives.

**Comment by etux** [comment]
Same issue here, uploading using `actions/upload-artifact@v3` works fine (I can't download the file from the UI and the file is correct). but when using `actions/download-artifact@v3` the downloaded file is corrupted. The file I am uploading/downloading is a jar file (just in case it makes any difference).

**Comment by nagarciah-mms** [comment]
Same here, still an issue. Fun fact: it just works If I don't use the "path" parameter in the download artifact section

**Comment by roeniss** [comment]
> Same here, still an issue. Fun fact: it just works If I don't use the "path" parameter in the download artifact section

This solved my problem too. I guess upload and download action has different logic for path resolution.
