### ISSUE TITLE
Upload is slow / Download is fast

### ISSUE THREAD

**Issue by fredrikhgrelland** [actions/upload-artifact#88]
**Describe the bug**
Unsure if this is a bug, as the code works, but is slow.
Opening this issue to get an understanding of what should be considered "slow."

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [ ] Linux
- [ ] Windows
- [x] Mac

**Run/Repo Url**
https://github.com/fredrikhgrelland/vagrant-hashistack/runs/794494146?check_suite_focus=true

**How to reproduce**
Use upload-artifact with any big file.

This one is ~1.7GB in size. It uploads in ~12 minutes, averaging at ~20Mb/s
Download of the same in download-artifact took 42 seconds.

**Additional context**
download-artifact is super fast to download the same file once uploaded.

**Comment by konradpabjan** [comment]
In general, uploads will always be slower than downloads. During upload, we need to perform a write operator in our blob storage to save everything. There is also some gzip compression that we do before starting the upload to reduce the amount of data that is actually in transit (this can take some time to do as well). During download, it's simply a read operation. 

If you turn on [step debugging](https://github.com/actions/toolkit/blob/master/docs/action-debugging.md#how-to-access-step-debug-logs) you can see the individual time that it takes to upload a file. I would always test with a few thousand files that are each a few KB in size. You should expect around 100ms per file.

For files that are over 4MB in size, the performance can start to vary significantly due to extra gzip compression we do and the fact that the upload is chunked. Some more information here: https://github.com/actions/toolkit/blob/master/packages/artifact/docs/additional-information.md#considerations

During periods of high-traffic, this 100ms time period might be more. If you're using a self-hosted runner, it will be also be slower as network latency starts to become a much bigger factor that we cannot control. Our Mac Pools are also in different data-centers compared to our Ubuntu and Windows VMs so expect slower uploads when using hosted Mac.

**Comment by monotek** [comment]
If uplading takes longer than creating the artifact i doubt it makes sense to use the function.

**Comment by aprilmintacpineda** [comment]
In my case:

```
With the provided path, there will be 452564 files uploaded
```

After >6 minutes, the progress was 0.7%

**Comment by punith-ganadinni** [comment]
We moved from gitlab to github. upload artifacts in gitlab was roughly 600% faster. Any explanation behind the same?

**Comment by Nearoo** [comment]
Same, artifact upload unusable due to upload taking 3 minutes for 500 MBs.
